name: deploy

on:
  push: 
    branches: 
    - feature/ci-cd

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.7
    services: 
      mysql: 
        image: mysql:latest
        ports: 
          - 3306:3306
    steps:
      - uses: actions/checkout@v1
      - name: Istall dependencies
        run:  | 
          chmod -R 777 scripts/dependencies.sh
          sh scripts/dependencies.sh
      - name: Test 
        run: | 
          chmod -R 777 scripts/test.sh
          sh scripts/test.sh
  